# Player Plot Configuration
Language file: en
Use /pplot root: false
Starting Plot Amount: 1
Maximum Plot Amount: 50
Plot Unit Size: 25
Plot pvp: true
Plot world blacklist:
  - example-world
Protection warning:
  particle: true
  sound: true
  message: true
# Database
Use database: false
host: 00.00.000.00
port: 3306
database: myDatabase
username: myUsername
password: myPassword
ssl: false
# Dynmap
Use dynmap: true
Show Plot Markers by Default: true
